authors:
  andresavila:
    name: Andres Avila
    description: Senior Data Engineer - AI-Powered Data Systems
    avatar: https://andresavila.io/assets/headshot.jpg
    url: https://www.linkedin.com/in/andres-avilaa/
